In [1]:
import numpy as np
import pandas as pd

In [2]:
float_data = pd.Series([1.2,-3.5,np.nan,0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
# None value is treated as na 
string_data = pd.Series(["aardvark",np.nan,None,"avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1,2,None],dtype ='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [11]:
data = pd.Series([1,np.nan,3.5,np.nan,7])

In [12]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [13]:
# dropna() to drop the na values
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1.,6.5,3.],[1,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3]])

In [15]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [17]:
# passsing how = all for only delete the rows that have all na values
data.dropna(how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan

In [19]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
# dropping the coulmns that have all na values
data.dropna(axis = "columns", how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [21]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [22]:
df

0         1         2
0  0.850207 -1.092494  1.002334
1 -1.097233 -1.224922  0.397866
2  0.014784  2.298523 -0.025337
3 -1.820809 -0.637999 -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [23]:
df.iloc[:4,1] = np.nan

In [24]:
df

0         1         2
0  0.850207       NaN  1.002334
1 -1.097233       NaN  0.397866
2  0.014784       NaN -0.025337
3 -1.820809       NaN -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [25]:
df.iloc[:2,2] = np.nan

In [26]:
df

0         1         2
0  0.850207       NaN       NaN
1 -1.097233       NaN       NaN
2  0.014784       NaN -0.025337
3 -1.820809       NaN -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [27]:
df.dropna()

0         1         2
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [28]:
df.dropna(thresh=2)

0         1         2
2  0.014784       NaN -0.025337
3 -1.820809       NaN -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [29]:
# fill the data in nan
df.fillna(0)

0         1         2
0  0.850207  0.000000  0.000000
1 -1.097233  0.000000  0.000000
2  0.014784  0.000000 -0.025337
3 -1.820809  0.000000 -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [30]:
# using fill na different values with help of dictionary
df.fillna({1:0.5,2:0})

0         1         2
0  0.850207  0.500000  0.000000
1 -1.097233  0.500000  0.000000
2  0.014784  0.500000 -0.025337
3 -1.820809  0.500000 -1.027949
4 -1.632713 -0.636024  0.556863
5  0.514200 -0.347643  0.837459
6  0.616196  0.338077  0.376084

In [31]:
df = pd.DataFrame(np.random.standard_normal((6,3)))
df

0         1         2
0 -0.017595  0.026051  0.098413
1 -1.265744 -1.017466 -0.119380
2  0.258952 -1.403697 -2.429669
3  1.502499 -1.478918 -1.221501
4  0.620313  1.198004  1.495104
5  0.346512 -1.041467  0.667643

In [32]:
df.iloc[2:,1] = np.nan
df

0         1         2
0 -0.017595  0.026051  0.098413
1 -1.265744 -1.017466 -0.119380
2  0.258952       NaN -2.429669
3  1.502499       NaN -1.221501
4  0.620313       NaN  1.495104
5  0.346512       NaN  0.667643

In [33]:
df.iloc[4:,2] = np.nan

In [34]:
df

0         1         2
0 -0.017595  0.026051  0.098413
1 -1.265744 -1.017466 -0.119380
2  0.258952       NaN -2.429669
3  1.502499       NaN -1.221501
4  0.620313       NaN       NaN
5  0.346512       NaN       NaN

In [35]:
df.ffill()

0         1         2
0 -0.017595  0.026051  0.098413
1 -1.265744 -1.017466 -0.119380
2  0.258952 -1.017466 -2.429669
3  1.502499 -1.017466 -1.221501
4  0.620313 -1.017466 -1.221501
5  0.346512 -1.017466 -1.221501

In [36]:
df.ffill(limit =2)

0         1         2
0 -0.017595  0.026051  0.098413
1 -1.265744 -1.017466 -0.119380
2  0.258952 -1.017466 -2.429669
3  1.502499 -1.017466 -1.221501
4  0.620313       NaN -1.221501
5  0.346512       NaN -1.221501

In [37]:
data = pd.Series([1.,np.nan,3.5,np.nan,7])

In [38]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [39]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

Data Transformation

In [40]:
data = pd.DataFrame({"k1": ["one","two"]*3 + ["two"],"k2" : [1,1,2,3,3,4,4]})

In [41]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [42]:
# show boolean series indicating whether each row is duplicate (compare with above rows)
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [44]:
data["v1"] = range(7)

In [45]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [46]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [47]:
data.drop_duplicates(subset= ["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [48]:
data.drop_duplicates(["k1","k2"],keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

Transforming Data Using a Function or Mapping

In [49]:
data = pd.DataFrame({
    "food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", 
             "bacon", "pastrami", "honey ham", "nova lox"],
    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
})

In [50]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

Replacing Values

In [51]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [52]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [53]:
# replace() 
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [54]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [55]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [56]:
data = pd.DataFrame(np.arange(12.).reshape((3,4)),index = ["Melbourne", "Sydney","Darwin"], columns = ["one","two","three","four"])

In [57]:
data

one  two  three  four
Melbourne  0.0  1.0    2.0   3.0
Sydney     4.0  5.0    6.0   7.0
Darwin     8.0  9.0   10.0  11.0

In [58]:
def transform(x):
    return x[:4].upper()

In [59]:
data.index.map(transform)

Index(['MELB', 'SYDN', 'DARW'], dtype='object')

In [60]:
data

one  two  three  four
Melbourne  0.0  1.0    2.0   3.0
Sydney     4.0  5.0    6.0   7.0
Darwin     8.0  9.0   10.0  11.0

In [61]:
data.index = data.index.map(transform)

In [62]:
data

one  two  three  four
MELB  0.0  1.0    2.0   3.0
SYDN  4.0  5.0    6.0   7.0
DARW  8.0  9.0   10.0  11.0

In [63]:
# For rename index
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Melb  0.0  1.0    2.0   3.0
Sydn  4.0  5.0    6.0   7.0
Darw  8.0  9.0   10.0  11.0

In [64]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [65]:
bins = [18,25,35,60,100]

In [66]:
age_categories = pd.cut(ages,bins)

In [67]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [68]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [69]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [70]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [71]:
pd.value_counts(age_categories)

C:\Users\User\AppData\Local\Temp\ipykernel_2776\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [72]:
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [73]:
group_names = ["Youth","YoungAdult","MiddleAged","Senior"]

In [74]:
# passing labels as group_names
pd.cut(ages,bins,labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [75]:
data = np.random.uniform(size=20)

In [76]:
data

array([0.76255362, 0.63357936, 0.43531072, 0.79723168, 0.0699347 ,
       0.33412145, 0.93625156, 0.92994293, 0.21524296, 0.6544641 ,
       0.82520909, 0.77086867, 0.94793966, 0.13222561, 0.43324289,
       0.57867537, 0.55560493, 0.52374074, 0.1483916 , 0.85902663])

In [77]:
# precision limits to number with 2 decimal places
pd.cut(data,4,precision=2)

[(0.73, 0.95], (0.51, 0.73], (0.29, 0.51], (0.73, 0.95], (0.069, 0.29], ..., (0.51, 0.73], (0.51, 0.73], (0.51, 0.73], (0.069, 0.29], (0.73, 0.95]]
Length: 20
Categories (4, interval[float64, right]): [(0.069, 0.29] < (0.29, 0.51] < (0.51, 0.73] < (0.73, 0.95]]

In [78]:
data = np.random.standard_normal(1000)

In [82]:
# qcut uses to make bins of same quantities
quartiles = pd.qcut(data,4,precision=2)

In [83]:
quartiles

[(-3.0799999999999996, -0.66], (-3.0799999999999996, -0.66], (-0.012, 0.61], (-3.0799999999999996, -0.66], (0.61, 3.04], ..., (-3.0799999999999996, -0.66], (-0.012, 0.61], (-0.012, 0.61], (0.61, 3.04], (-0.66, -0.012]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0799999999999996, -0.66] < (-0.66, -0.012] < (-0.012, 0.61] < (0.61, 3.04]]

In [287]:
quartiles.value_counts()

(-3.0799999999999996, -0.66]    250
(-0.66, -0.012]                 250
(-0.012, 0.61]                  250
(0.61, 3.04]                    250
Name: count, dtype: int64

In [85]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [86]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.024290    -0.046573     0.011014    -0.030278
std       1.029050     0.992976     0.972949     0.970616
min      -2.957743    -3.244879    -3.332691    -2.880263
25%      -0.657359    -0.737965    -0.645513    -0.654768
50%       0.022363    -0.007481     0.018461    -0.052404
75%       0.702969     0.626088     0.647884     0.640659
max       4.131459     3.591107     3.077073     3.563606

In [87]:
# finding columns exceding absoulte value
col = data[1]

In [88]:
col[col.abs()>3]

269    3.591107
712   -3.244879
Name: 1, dtype: float64

In [89]:
# selecting all rows that have exceding value of 3 0r -3 using any method
data[(data.abs()>3).any(axis="columns")]

0         1         2         3
67   3.264244 -0.833589  0.782594 -2.084939
148  2.209339 -0.081672  0.459722  3.015289
210  4.131459  0.861350  0.677937  1.229997
253 -1.037520 -0.947170  0.909034  3.354538
269  0.352145  3.591107 -0.638640  0.987029
296 -0.214234  0.125983 -3.332691  0.486642
302  3.230115 -1.443169  1.312075 -1.378505
349  3.215808  1.100448  0.369992  1.089399
439  0.565537  1.800340  0.216782  3.563606
462  3.218568  0.127230 -0.325209 -0.009741
467 -0.513152 -0.134391  3.077073  0.591015
548 -0.797906 -1.695712  0.945179  3.123413
712 -0.688280 -3.244879 -1.050871  1.983879
902  3.052936 -0.544362  0.858327 -0.820722

In [90]:
# np.sign return 1,0 or -1 depending on sign +,0 and -
data[data.abs() >3] = np.sign(data) * 3

In [91]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.022177    -0.046920     0.011270    -0.031335
std       1.022179     0.990221     0.971621     0.967070
min      -2.957743    -3.000000    -3.000000    -2.880263
25%      -0.657359    -0.737965    -0.645513    -0.654768
50%       0.022363    -0.007481     0.018461    -0.052404
75%       0.702969     0.626088     0.647884     0.640659
max       3.000000     3.000000     3.000000     3.000000

In [92]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0  1.0 -1.0
2 -1.0 -1.0  1.0  1.0
3 -1.0  1.0  1.0  1.0
4 -1.0  1.0 -1.0 -1.0

Permutation and Random Sampling

In [93]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [94]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [95]:
sampler = np.random.permutation(5)

In [96]:
sampler

array([3, 1, 0, 4, 2], dtype=int32)

In [97]:
# Arranging row based on sampler in dataset
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [98]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [99]:
column_sampler = np.random.permutation(7)

In [100]:
column_sampler

array([5, 4, 1, 2, 0, 3, 6], dtype=int32)

In [101]:
# by passing axis = columns we select permutation of columns
df.take(column_sampler, axis = "columns")

5   4   1   2   0   3   6
0   5   4   1   2   0   3   6
1  12  11   8   9   7  10  13
2  19  18  15  16  14  17  20
3  26  25  22  23  21  24  27
4  33  32  29  30  28  31  34

In [102]:
# taking sample from dataframe
df.sample(n=3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [103]:
choices = pd.Series([5,7,-1,6,4])

In [104]:
choices.sample(n=10, replace=True)

4    4
3    6
1    7
0    5
4    4
1    7
4    4
1    7
1    7
2   -1
dtype: int64

Computing Indicator/Dummy Variable

In [105]:
df = pd.DataFrame({'key':["b","b","a","c","a","b"],
                   "data1" : range(6)})

In [106]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [107]:
# get.dummies() to convert dummy 
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [108]:
# Adding prefix in dummies
dummies = pd.get_dummies(df["key"],prefix = "key")

In [109]:
df_with_dummy = df[["data1"]].join(dummies)

In [110]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [111]:
mnames = ["movie_id","title","genres"]

In [112]:
movies = pd.read_table(r"D:\PythonForDataAnalysis\movies.dat",sep ="::", header = None, names = mnames, engine ="python")

In [113]:
movies.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [114]:
movies.head(10)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [115]:
dummies = movies["genres"].str.get_dummies("|")

In [116]:
dummies.iloc[:10,:6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [117]:
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [118]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [119]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [120]:
np.random.seed(12345)

In [121]:
values = np.random.uniform(size=10)

In [122]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [123]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [124]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [125]:
s = pd.Series([1,2,3,None])

In [126]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [127]:
s.dtype

dtype('float64')

In [128]:
# making data type Int64Dtype()
s = pd.Series([1,2,3,None], dtype = pd.Int64Dtype())

In [129]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [130]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [131]:
s = pd.Series(['one','two',None,'three'], dtype = pd.StringDtype())

In [132]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [133]:
df = pd.DataFrame({'A' : [1,2,None,4],
                   'B' : ["one","two","three",None],
                   'C' : [False,None,False,True]})

In [134]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [135]:
# astype to define data types
df["A"] = df["A"].astype("Int64")

In [136]:
df["B"] = df["B"].astype("string")

In [137]:
df ["C"] = df["C"].astype("boolean")

In [138]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

String Mainpulation

In [139]:
val = "a,b, guido"

In [140]:
val.split(",")

['a', 'b', ' guido']

In [141]:
pieces = [x.strip() for x in val.split(",")]

In [142]:
pieces

['a', 'b', 'guido']

In [143]:
first, second, third = pieces

In [144]:
first + "::" + second + "::" + third

'a::b::guido'

In [145]:
"::".join(pieces)

'a::b::guido'

In [146]:
"guido" in val

True

In [147]:
val.index(",")

1

In [148]:
val.find(":")

-1

In [149]:
import re
# re module helps to pattern matching, subsitute and splitting

In [150]:
text = "foo bar\t baz  \tqux"

In [151]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [154]:
regex = re.compile(r"\s+")

In [155]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [157]:
# for patterns
regex.findall(text)

[' ', '\t ', '  \t']

In [158]:
text = """Anush anush@google.com
Anush anushgiri72@gmail.com
fug Fugitivecos43@gmail.com
Giri giriyahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [160]:
#re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags= re.IGNORECASE)

In [161]:
regex.findall(text)

['anush@google.com', 'anushgiri72@gmail.com', 'Fugitivecos43@gmail.com']

In [162]:
m = regex.search(text)

In [163]:
m

<re.Match object; span=(6, 22), match='anush@google.com'>

In [164]:
text[m.start():m.end()]

'anush@google.com'

In [165]:
print(regex.match(text))

None


In [166]:
print(regex.sub("Hello",text))

Anush Hello
Anush Hello
fug Hello
Giri giriyahoo.com


In [167]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [168]:
m = regex.match("anush@bright.net")

In [169]:
m.groups()

()

In [170]:
data = {"Anush" : "anushgiri72@gmail.com", "giri": "Giri72@gmail.com", "a":"a@gmail.com","b":np.nan}

In [171]:
data = pd.Series(data)

In [172]:
data

Anush    anushgiri72@gmail.com
giri          Giri72@gmail.com
a                  a@gmail.com
b                          NaN
dtype: object

In [173]:
data.isna()

Anush    False
giri     False
a        False
b         True
dtype: bool

In [174]:
data.str.contains("gmail")

Anush    True
giri     True
a        True
b         NaN
dtype: object

In [175]:
data_as_string_ext = data.astype('string')

In [176]:
data_as_string_ext

Anush    anushgiri72@gmail.com
giri          Giri72@gmail.com
a                  a@gmail.com
b                         <NA>
dtype: string

In [177]:
data_as_string_ext.str.contains("gmail")

Anush    True
giri     True
a        True
b        <NA>
dtype: boolean

In [178]:
 pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [179]:
data.str.findall(pattern, flags=re.IGNORECASE)

Anush    [(anushgiri72, gmail, com)]
giri          [(Giri72, gmail, com)]
a                  [(a, gmail, com)]
b                                NaN
dtype: object

In [180]:
# makes tuples
matches = data.str.findall(pattern,flags=re.IGNORECASE).str[0]

In [181]:
matches

Anush    (anushgiri72, gmail, com)
giri          (Giri72, gmail, com)
a                  (a, gmail, com)
b                              NaN
dtype: object

In [182]:
# getting items from list
matches.str.get(1)

Anush    gmail
giri     gmail
a        gmail
b          NaN
dtype: object

In [183]:
data.str[:5]

Anush    anush
giri     Giri7
a        a@gma
b          NaN
dtype: object

In [184]:
data.str.extract(pattern, flags = re.IGNORECASE)

0      1    2
Anush  anushgiri72  gmail  com
giri        Giri72  gmail  com
a                a  gmail  com
b              NaN    NaN  NaN

In [185]:
values = pd.Series(['apple','orange','apple','apple']*2)

In [186]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [188]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [190]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [191]:
values = pd.Series([0,1,0,0]*2)

In [192]:
dim = pd.Series(['apple','orange'])

In [193]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [194]:
dim

0     apple
1    orange
dtype: object

In [195]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [207]:
fruits = ['apple','orange','apple','apple'] * 2
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [208]:
N = len(fruits)

In [209]:
rng = np.random.default_rng(seed=12345)

In [212]:
df = pd.DataFrame({'fruit' : fruits,
                   'basket_id' : np.arange(N),
                   'count' : rng.integers(3,15,size =N),
                   'weight' : rng.uniform(0,4,size=N)},
                  columns = ['basket_id','fruit','count','weight'])

In [213]:
df

basket_id   fruit  count    weight
0          0   apple     11  2.789814
1          1  orange     11  1.305891
2          2   apple      4  2.935713
3          3   apple      4  0.880540
4          4   apple      6  0.326378
5          5  orange      8  0.639582
6          6   apple      3  1.360401
7          7   apple     13  1.860773

In [214]:
fruit_cat = df['fruit'].astype('category')

In [215]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [216]:
c = fruit_cat.array

In [217]:
type(c)

pandas.core.arrays.categorical.Categorical

In [218]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [219]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [220]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [221]:
df['fruit'] = df['fruit'].astype('category')

In [222]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [223]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [224]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [225]:
my_categories.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [226]:
categories = ['foo','bar','baz']

In [227]:
codes = [0,1,2,0,0,1]

In [228]:
my_cats_2 = pd.Categorical.from_codes(codes,categories)

In [229]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [231]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered = True)

In [232]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [234]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [235]:
rng = np.random.default_rng(seed = 12345)

In [236]:
draws = rng.standard_normal(1000)

In [237]:
draws

array([-1.42382504e+00,  1.26372846e+00, -8.70661738e-01, -2.59173235e-01,
       -7.53433070e-02, -7.40884652e-01, -1.36779270e+00,  6.48892802e-01,
        3.61058113e-01, -1.95286306e+00,  2.34740965e+00,  9.68496906e-01,
       -7.59387180e-01,  9.02198274e-01, -4.66953173e-01, -6.06895187e-02,
        7.88844345e-01, -1.25666813e+00,  5.75857514e-01,  1.39897899e+00,
        1.32229806e+00, -2.99698515e-01,  9.02919341e-01, -1.62158273e+00,
       -1.58189261e-01,  4.49483932e-01, -1.34360107e+00, -8.16875907e-02,
        1.72473993e+00,  2.61815943e+00,  7.77361344e-01,  8.28633196e-01,
       -9.58988313e-01, -1.20938829e+00, -1.41229201e+00,  5.41546830e-01,
        7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  

In [238]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [239]:
bins = pd.qcut(draws,4)

In [240]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [241]:
bins = pd.qcut(draws,4,labels = ['Q1','Q2','Q3','Q4'])

In [242]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [243]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [244]:
bins = pd.Series(bins, name = 'quartile')

In [245]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

C:\Users\User\AppData\Local\Temp\ipykernel_2776\1051773774.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())


In [247]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [248]:
results.quartile

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [249]:
N = 10_000_000

In [250]:
labels = pd.Series(['foo','bar','baz','qux']*(N//4))

In [251]:
labels

0          foo
1          bar
2          baz
3          qux
4          foo
          ... 
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: object

In [252]:
categories = labels.astype('category')

In [254]:
# memory
labels.memory_usage(deep= True)

520000132

In [255]:
categories.memory_usage(deep= True)

10000512

In [256]:
s = pd.Series(['a','b','c','d']*2)

In [257]:
cat_s = s.astype('category')

In [258]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [259]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [260]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [261]:
actual_categories = ['a','b','c','d','e']

In [262]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [263]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [265]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [266]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [267]:
# removing unused categories
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [268]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [270]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [271]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [273]:
cat_s.cat.add_categories('e')

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [274]:
cat_s.cat.as_ordered()

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a' < 'b' < 'c' < 'd']

In [276]:
cat_s.cat.as_unordered()

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [279]:
cat_s.cat.rename_categories(['a','f','e','g'])

0    a
1    f
2    e
3    g
4    a
5    f
6    e
7    g
dtype: category
Categories (4, object): ['a', 'f', 'e', 'g']

In [280]:
cat_s = pd.Series(['a','b','c','d']*2 , dtype = 'category')

In [282]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [283]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [284]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [286]:
# getting dummies
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True

In [288]:
movies = pd.read_table(r"D:\PythonForDataAnalysis\movies.dat",sep ="::", header = None, names = mnames, engine ="python")

In [289]:
movies.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [292]:
movie_genres = movies.genres.str.get_dummies("|")

In [293]:
movie_genres

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [296]:
movie_genres.head()

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0       0          0          1           1       1      0            0   
1       0          1          0           1       0      0            0   
2       0          0          0           0       1      0            0   
3       0          0          0           0       1      0            0   
4       0          0          0           0       1      0            0   

   Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0      0        0          0       0        0        0        0       0   
1      0        1          0       0        0        0        0       0   
2      0        0          0       0        0        0        1       0   
3      1        0          0       0        0        0        0       0   
4      0        0          0       0        0        0        0       0   

   Thriller  War  Western  
0         0    0        0  
1         0    0        0  
2         0    0        0  
3         0    0        0  
4         0    0        0

In [297]:
movies.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [299]:
movie_genres.join(dummies.add_prefix("Genres_"))

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  ...  Genres_Fantasy  Genres_Film-Noir  \
0         0        0          0  ...               0                 0   
1         0        1          0  ...               1                 0   
2         0        0          0  ...               0                 0   
3         1        0          0  ...               0                 0   
4         0        0          0  ...               0                 0   
...     ...      ...        ...  ...             ...               ...   
3878      0        0          0  ...               0                 0   
3879      1        0          0  ...               0                 0   
3880      1        0          0  ...               0                 0   
3881      1        0          0  ...               0                 0   
3882      1        0          0  ...               0                 0   

      Genres_Horror  Genres_Musical  Genres_Mystery  Genres_Romance  \
0                 0               0               0               0   
1                 0               0               0               0   
2                 0               0               0               1   
3                 0               0               0               0   
4                 0               0               0               0   
...             ...             ...             ...             ...   
3878              0               0               0               0   
3879              0               0               0               0   
3880              0               0               0               0   
3881              0               0               0               0   
3882              0               0               0               0   

      Genres_Sci-Fi  Genres_Thriller  Genres_War  Genres_Western  
0                 0                0           0               0  
1                 0                0           0               0  
2                 0                0           0               0  
3                 0                0           0               0  
4                 0                0           0               0  
...             ...              ...         ...             ...  
3878              0                0           0               0  
3879              0                0           0               0  
3880              0                0           0               0  
3881              0                0           0               0  
3882              0                1           0               0  

[3883 rows x 36 columns]

In [302]:
movie_genres.iloc[1]

Action         0
Adventure      1
Animation      0
Children's     1
Comedy         0
Crime          0
Documentary    0
Drama          0
Fantasy        1
Film-Noir      0
Horror         0
Musical        0
Mystery        0
Romance        0
Sci-Fi         0
Thriller       0
War            0
Western        0
Name: 1, dtype: int64